### ISSUE TITLE
Option clash for package color

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#3]
! LaTeX Error: Option clash for package color.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.34 \RequirePackage
                    {forloop}

**Comment by simas0** [comment]
Refere-se à linha 34 do pacote livroabertopages. Esse erro geralmente indica que o pacote color foi chamado mais de uma vez. Mas o pacote forloop define apenas dois comandos `\forloop` e `\forLoop`. Sugiro que procure por esses termos em todos os arquivos de texto da pasta (tem comando para isso no terminal do Ubuntu). Caso não sejam utilizados, comentamos a linha 34 e o erro deve ser resolvido.

**Comment by simas0** [comment]
Percebi que o pacote livroabertopages chama os pacotes color e xcolor, acredito que não sejam necessários os dois. Eu comentei o primeiro e: não vi diferença no arquivo compilado e o erro sumiu.
