### ISSUE TITLE
Livro do professor: Listas não quebram linha como deve, e passam então para fora da página

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#34]
![image](https://user-images.githubusercontent.com/40038251/77106436-d508fd80-69fd-11ea-9c03-76608249b31c.png)

**Comment by simas0** [comment]
This issue: Column width is not respected in commented edition when using itemize.

 I managed to fix this creating a tcolorbox theorem, setting its width in the preamble and inserting the itemize on it. But new problems arise (see #40)
