### ISSUE TITLE
Pacote Livro Aberto não funciona bem junto  do commedit

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#36]
Mas se tirarmos os pacotes  livroabertoheadings e livroabertopage funciona, porém com problemas no itemize e ainda sem o enumerate funcionar propriamente

**Comment by simas0** [comment]
Ao que me parece o commedit não é compatível com os seguintes comandos, que podem ser usados no headings.

```
\RequirePackage{atbegshi}
\AtBeginShipout{\Header}
\AtBeginShipoutFirst{\Header}
```
