### ISSUE TITLE
Option clash for package babel

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#4]
! LaTeX Error: Option clash for package babel.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.45 \RequirePackage
                    {blindtext}

**Comment by simas0** [comment]
Parece que o pacote babel é chamado no pacote blindtext. Uma pergunta é se os comandos definidos pelo pacote blindtext são usados no projeto.

http://linorg.usp.br/CTAN/macros/latex/contrib/blindtext/blindtext.pdf

**Comment by simas0** [comment]
O problema era que o pacote babel era chamado no pacote livroabertopage e no arquivo aluno.tex, comentei a linha em que babel era chamado no pacote livroabertopage e o erro sumiu.
