### ISSUE TITLE
Tcbtheorem does not break properly between columns in commented edition

### ISSUE THREAD

**Issue by simas0** [livro-aberto/tex-design-development#40]
In  #34, @tarsobcaldas, shows that column width is not respected in commented edition when using itemize. I managed to fix this creating a tcolorbox theorem, setting its width in the preamble and inserting the itemize on it. But so I stopped at this new issue: 

if the box is bigger than the remaining vertical space for the column, then the tcbtheorem does not break properly into the columns.

Here is an example of the code and the issue:

`\documentclass{book}
\usepackage[papersize={204mm,275mm}, top=17mm,
bottom=17mm, outer=22mm, inner=20mm, includeheadfoot=false]{geometry}
\usepackage{commedit}

\begin{commeditPreamble}{commented.tex}
  \documentclass{book}
  \usepackage[papersize={230mm,288mm}, top=15mm,
  bottom=17mm, outer=11mm, inner=4.5mm, includeheadfoot=false]{geometry}
  \usepackage{kantlipsum}
  \usepackage{ragged2e}
  \usepackage{booktabs}
  \usepackage{commedit}
  \basepageargs{width=140mm}
  \commentsHook{\RaggedRight\parskip=0pt\parindent=1em\relax}

 \usepackage[breakable,theorems]{tcolorbox}
 \newtcbtheorem{objetivos}{Atividade}{
  breakable,
  width=60mm,
}{Th}

\end{commeditPreamble}
\begin{document}

\mainmatter
\chapter{Some thoughts}

\begin{commeditComments}
  \begin{objetivos}{}{}
      \kant[2]
  \end{objetivos}
  \end{commeditComments}

\end{document}
`

and the result

![image](https://user-images.githubusercontent.com/16407253/78567752-88903100-77f7-11ea-89da-72dcf217d503.png)

**Comment by tarsobcaldas** [comment]
I've tried with the environments framed, xeboiboites, putting enforce breakable on the tcolorbox envirnment and this custom environment:

\newbox\totalbox
\newbox\partialbox
\newdimen\partialboxdim

\newenvironment{continueframe}{%
    \advance\linewidth-2\fboxsep
    \advance\linewidth-2\fboxrule
    \hsize=\linewidth
    \partialboxdim=\dimexpr\pagegoal-\pagetotal-\pageshrink-6pt-\baselineskip\relax
    \setbox\totalbox=\vbox\bgroup\begingroup
}{%
    \endgraf\endgroup\egroup
    \setbox\partialbox=\vsplit\totalbox to\partialboxdim
    \par\smallskip
    \hbox{\fbox{\vbox{\unvbox\partialbox}}}\nopagebreak
    \par\smallskip\mbox{}\hfill\textbf{Continued on next page}\par\pagebreak%
    \hbox{\fbox{\vbox{\noindent\textbf{Contuined from last page}\par\smallskip\unvbox\totalbox}}}%
    \par\medskip
}

All of them result in similar or worse results of the tcolorbox problem listed above

**Comment by borisveytsman** [comment]
`tcbtheorem` uses its own output routine.  This clashes with the commedit output routine.  I'd suggest using unbreakable boxes only
