### ISSUE TITLE
\exercise undefined

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#5]
! LaTeX Error: \exercise undefined.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.389 \renewcommand{\exercise}

**Comment by simas0** [comment]
Você informou dois erros aqui e os problemas eram exatamente o que o compilador informou.

Erro 1:
No pacote livroabertoheadings.sty o comando \exercise estava sendo redefinido sem ter sido definido antes. Troquei `\renewcommand{\exercise}` por `\newcommand{\exercise}` e o erro sumiu.

Erro 2:
No pacote livroabertoboxes.sty, que é chamado depois do livroabertoheadings.sty, estava sendo definido o ambiente `exercise` por meio do comando `\NewEnviron{exercise}{%`. Comentei a definição e o erro sumiu.

**Comment by simas0** [comment]
**Importante:** A definição do ambiente de exercícios no pacote livroabertoboxes.sty parece ser a forma certa de se fazer, o código promissor, talvez já até funcione. Mas é usada com `\begin{exercise}` e não com `\exercise`.
