### ISSUE TITLE
I do not know the key '/tcb/jigsaw' and I am going to  ignore it.

### ISSUE THREAD

**Issue by tarsobcaldas** [livro-aberto/tex-design-development#6]
! Package pgfkeys Error: I do not know the key '/tcb/jigsaw' and I am going to 
ignore it. Perhaps you misspelled it.

See the pgfkeys package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.6 \chapter{Probabilidade}

**Comment by simas0** [comment]
No pacote livroabertoheadings são definidos as caixas do "O quê?" (whatbox) e "Por quê?" (whybox) do início do capítulo. Nessas definições é usada a opção jigsaw, do tcolorbox. Mas não entendo o motivo do erro. Será necessária uma biblioteca do tcolorbox para se usar esta opção?

**Comment by simas0** [comment]
Defini a caixa openningbox em substituição a whatbox e à whybox sem usar a opção jigsaw, mas ainda é um mistério que a caixa esteja transparente sem essa opção. O erro está resolvido.
